<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;
use Psr\Log\LoggerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

function custom_user_roles_form_user_register_form_alter(array &$form, FormStateInterface $form_state, $form_id)
{
  $form['account']['role'] = [
    '#type' => 'select',
    '#title' => t('Role'),
    '#options' => [
      'vendor' => t('Vendor'),
      'customer' => t('Customer'),
    ],
    '#required' => TRUE,
  ];
  $form['actions']['submit']['#submit'][] = 'custom_user_roles_form_user_register_form_submit';
}

function custom_user_roles_form_user_register_form_submit(array &$form, FormStateInterface $form_state)
{
  $values = $form_state->getValues();

  $uid = $values['uid'];
  $role = $values['role'];
  $password = $values['pass'];

  $user = User::load($uid);
  if ($user !== NULL) {
    $user->setPassword($password);
    $user->addRole($role);
  }
  $user->save();
}