<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

function rating_sync_entity_presave(EntityInterface $entity)
{
    if ($entity instanceof NodeInterface && $entity->getType() === 'cart') {
        $product_reference = $entity->get('field_product')->entity;
        if ($product_reference) {
            $fivestar_field = $entity->get('field_rating');
            $rating_value = $fivestar_field->getValue()[0]['rating'];
            $product_reference->set('field_rating', $rating_value);
            $product_reference->save();
        }
    }
}